version: 0.2
phases:
 install:
   commands:
     - npm install
 pre_build:
   commands:
     - npm run build
 build:
   commands:
     - npm run deploy
 post_build:
   commands:
     - echo "post_build step"